### ISSUE TITLE
ojAlgo version

### ISSUE THREAD

**Issue by apete** [sfeilmeier/ems-energy-model#1]
I see you're using ojAlgo v50.0.1. Although that's a fairly recent version, v51.0.0 had specific LP performance improvements that should benefit you.

Further there is some preliminary work to improve the IntegerSolver: https://github.com/optimatika/ojAlgo/tree/IntegerStrategy

I'd be very interested to know if that improves things for you, or not.

**Comment by pooran-c** [comment]
No, It did not improve. In fact, it takes a longer time to optimize.
Version : 50.0.1
Time: 21278ms

Version : 51.0.0
Time: 202721ms

**Comment by apete** [comment]
That's strange! Between those two versions there are no changes to the `IntegerSolver`.

There are major changes to the `LinearSolver` (much faster) and minor to `ExpressionsBasedModel`. Since the `LinearSolver` performs so much better I would assume most (linear) MIP models to finish faster, and the cases I tested confirmed that.

Now with v51.1.0 I'm making changes to the `IntegerSolver`. What's required to run your test case? I'd like to see what's going on. Do you just run the main method of the `EnergyApp`? Is that the test you're referring to?

**Comment by apete** [comment]
It seems that with v51.0.0 one (or some) of the LP node problems take very long. That's most likely something that can be tweaked away (code change or usage configuration, don't know the exact issue).

But you have another problem. You're not finding the optimal solution.

It seems there are several different solutions that are very close in terms of the objective value. When you set the `mip_gap` to 1E-2 the solver will stop at the very first solution it finds.

I tried with v51.1.0-SNAPSHOT that I have. It works well, and it shows you need 5 digits precision to find the optimal solution. On my machine (seems a bit faster than yours) that takes about 1min. The execution time is roughly halved with each digit precision not required. Down to about 4s – that's about the time it takes to find a first solution.

**Comment by apete** [comment]
https://www.ojalgo.org/2022/03/mip-strategy-configuration/
